id: big-calldata-tx-test
name: "Big Calldata TX Test"
timeout: 30m
config:
  walletPrivkey: ""
  transactionCount: 1000
  transactionsPerBlock: 10
  calldataSize: 1000
  transactionGasLimit: 5000000
tasks:
- name: check_clients_are_healthy
  title: "Check if at least one client is ready"
  timeout: 5m
  config:
    minClientCount: 1

# generate calldata
- name: run_shell
  title: "Run shell command"
  config:
    shell: "bash"
    envVars:
      calldataSize: "calldataSize"
    command: |
      echo "Generate calldata with $calldataSize zero bytes"
      calldata="0x$(eval "printf '00%.0s' {1..$calldataSize}")"
      childWallets=$(( transactionCount / 100 > 1 ? transactionCount / 100 : 1 ))
      echo $childWallets
      echo "::set-var calldata $calldata"
      echo "::set-var childWallets $childWallets"
      echo "yea"

- name: check_consensus_sync_status
  title: "Wait for chain activity (slot >= 5)"
  timeout: 1h
  config:
    minSlotHeight: 5

# send big calldata transactions
- name: generate_eoa_transactions
  title: "Send ${transactionCount} big calldata transactions"
  config:
    refillMinBalance: 1000000000000000000000 # 1000 ETH
    randomTarget: true
    amount: 0
    awaitReceipt: true
  configVars:
    # max 100 pending tx per wallet to avoid nonce gap limits
    childWallets: childWallets
    limitTotal: "transactionCount"
    limitPerBlock: "transactionsPerBlock"
    limitPending: "transactionsPerBlock"
    privateKey: "walletPrivkey"
    gasLimit: "transactionGasLimit"
    callData: "calldata"

- name: "sleep"
  title: "Wait 30sec to clear up pending transactions"
  config:
    duration: 30s

- name: run_tasks_concurrent
  title: "Check chain stability"
  timeout: 1h
  config:
    tasks:
    - name: check_consensus_finality
      title: "Check consensus chain finality"
      config:
        minFinalizedEpochs: 2
        maxUnfinalizedEpochs: 3
    - name: check_consensus_attestation_stats
      title: "Check consensus attestation stats"
      config:
        minTargetPercent: 98
        minHeadPercent: 80
    - name: check_consensus_reorgs
      title: "Check consensus reorgs"
      config:
        maxReorgsPerEpoch: 2
        minCheckEpochCount: 1
    - name: check_consensus_forks
      title: "Check consensus forks"
